export const ORDER_ADD_REQUEST = 'ORDER_ADD_REQUEST';
export const ORDER_ADD_SUCCESS = 'ORDER_ADD_SUCCESS';
export const ORDER_ADD_FAIL = 'ORDER_ADD_FAIL';
export const ORDER_ADD_RESET = 'ORDER_ADD_RESET';


export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST';
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS';
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL';