export const ORDER_ADD_REQUEST = 'ORDER_ADD_REQUEST';
export const ORDER_ADD_SUCCESS = 'ORDER_ADD_SUCCESS';
export const ORDER_ADD_FAIL = 'ORDER_ADD_FAIL';
export const ORDER_ADD_RESET = 'ORDER_ADD_RESET';
